// The story spine comes from the campaign bible. Runnable procedures are new for this free edition.
export const sessions = [
  {
    id: 0, title: 'Bring Mark Back', act: 'Act I - The city slips',
    purpose: 'Bring the crew together and teach SWADE through an urgent shared job.',
    readAloud: 'The portal frame is taller than the garage door. Its cables are labeled in handwriting you recognize. Through the empty center, someone knocks three times. A voice says: “I found the exit. Please tell me you found the entrance.”',
    essentialClues: ['Mark crossed passages that opened on a schedule.', 'Somewhere outside, living worlds are kept as collections. Mark remembers a label, not an explanation.'],
    clock: {id:'portal', label:'Portal instability', max:3, trigger:'Fill one box at the end of a task round while the portal remains unfinished.', consequence:'Mark arrives with collateral trouble. The return is never cancelled.'},
    scenes: [
      {id:'0-plan',title:'Agree the return',prompt:'Ask each player what their hero contributes and what they want Mark to find waiting.',procedure:'Let the crew examine the frame and choose three feeds: power, alignment, and physical stability. No roll is needed to discover these jobs. A successful Notice, Electronics, or Repair roll spots a scorched label and allows the group to choose where the first complication appears. Give new players one ordinary roll before introducing the larger task.',clue:'A strip of tape says: “Keep an anchor at both ends. Do not wait for the third pulse.”'},
      {id:'0-build',title:'Build the portal',prompt:'Open the core Dramatic Task reference. Offer power, alignment, bracing, or Support.',procedure:'Tutorial task: 8 group Task Tokens in 3 rounds. Electronics or Repair operates a feed; Athletics braces the frame; a convincing alternative uses the appropriate Trait. Run Action Cards and complications using SWADE. In round 2, two rift leeches attach to exposed feeds. A player can remove, lure, or fight them, or Support someone doing it. Explain each rule at the moment it becomes useful. Do not require every character to possess technical skills.',clue:'The feed display counts three pulses between neighboring realities.'},
      {id:'0-return',title:'Let the first mistake matter',prompt:'Bring Mark through. Ask the players which thing they protect when the portal kicks.',procedure:'On success, Mark arrives and the crew secures the frame. If the goal is missed or the task ends early, he still arrives; choose one cost with the players: the frame is ruined, a leech remains loose, or a harmless but unsettling patch of wrong weather follows him. Use a brief combat with remaining leeches only if the group wants that tutorial. Mark describes contradictory corridors and a hard departure window. He knows nothing about Calder’s purchase.',clue:'Time windows and current can guide a route, but neither supplies a destination.'},
    ],
    outcomes: {success:'Mark returns; the working frame can later supply a spare anchor.',partial:'Mark returns with one chosen cost. Record it and make it visible in Session 1.',failure:'Mark returns after a destructive kick. The crew salvages the route notebook and continues. An injured or Incapacitated hero is handled with core rules and care; failure does not erase their agency.'},
    next:'Spend the next gathering with the Chicago the crew wanted to come home to. End this one on reunion, not the ownership explanation.'
  },
  {
    id:1,title:'Chicago Is Safe',act:'Act I - The city slips',
    purpose:'Make the ten quiet years matter before reality becomes visibly unreliable.',
    readAloud:'The city looks like home. The train arrives when the sign says it will. A shopkeeper knows your order. Then a street name changes while you are looking at it, and everybody else seems certain it was always that way.',
    essentialClues:['Continuity errors cluster near newly installed weatherization panels.', 'At least one witness remembers the change. Public records insist nothing changed.'],
    clock:null,
    scenes:[
      {id:'1-home',title:'Visit something worth saving',prompt:'Use a place the players chose on their reunion sheets.',procedure:'Invite each player to introduce one local person, then confirm the invention with the group. Mark can tell one fragment from his route without a lore monologue. Use Persuasion, Common Knowledge, or Research only when a character takes a risk or wants privileged access. Ordinary friendly conversation succeeds without dice. Introduce contractor stickers on replacement panels as scenery.',clue:'The same contractor seal appears on two apparently unrelated repairs.'},
      {id:'1-error',title:'One harmless error, then one costly error',prompt:'Change a sign; then let a crossing briefly lead to the wrong platform.',procedure:'Give the group an obvious observation first: the station announcement names a street that nobody agrees about. Next, one civilian is stranded on a platform visible through an impossible doorway. A cooperative rescue uses one suitable Trait roll per participating hero or a core Quick Encounter. A failed roll costs the crew a broken tool, attention from security, or extra time; the civilian remains reachable through a mundane service exit. Never require a roll to notice the doorway.',clue:'The civilian saw the panel crew working before the error began.'},
      {id:'1-cartoon',title:'The first undeniable cartoon',prompt:'Introduce Pip, an original toon-bodied person, carrying a painted umbrella.',procedure:'Pip steps through the platform door. Their shadow takes a moment to catch up. They are frightened, capable of explaining their own needs, and not an enemy. Ask whether the crew offers shelter, containment, investigation, or an escort. Each is a valid next action. A failed Persuasion roll makes Pip cautious; food, patience, or a trusted witness earns a second conversation without another required check.',clue:'Pip’s neighborhood is real too. Its physical rules were separate until the shaking began.'},
    ],
    outcomes:{success:'The crew has a witness, an ally, and a panel seal to investigate.',partial:'The cartoon arrival is witnessed publicly. Contractors can identify the crew; Pip still offers the essential information.',failure:'The crew loses Pip in the confusion. Pip leaves the umbrella and a route mark; a civilian witness can lead them to the next incursion.'},
    next:'Give the crew its first Advance. Ask how it prepares for another overlap, then bring the cartoon gathering to a chosen neighborhood.'
  },
  {
    id:2,title:'Ink and Paint',act:'Act I - The city slips',
    purpose:'Make coalescence tangible through rescue, containment, and conflicting physical rules.',
    readAloud:'A bus brakes for a painted crosswalk. The crosswalk lifts off the road like a ribbon. On one side, people run as if gravity has stopped listening. On the other, people are still expecting gravity to work.',
    essentialClues:['Calder Restoration delivered specialized replacement panels before the incident.', 'A Thompson environmental-control routing mark is on the dispatch sheet.'],
    clock:{id:'danger',label:'Public danger',max:6,trigger:'Fill one box when a rescue round ends with nobody addressing civilians.',consequence:'A second group becomes stranded. Rescue remains possible; ask which group the heroes reach first.'},
    scenes:[
      {id:'2-rules',title:'Establish the local physics',prompt:'Show one reversible oddity before anyone risks their life.',procedure:'A ladder can bend without breaking, a painted door opens onto the other side of the same wall, and falling objects hang for one heartbeat before dropping. Keep those three rules consistent for the encounter. Let harmless testing establish them without rolls. A risky crossing uses Athletics, a suitable technical skill, or a player’s creative proposal. Announce a failed crossing’s cost before the roll; an ally or alternate door prevents an instant dead end.',clue:'Pip recognizes the neighborhood as a real place, not a hallucination or invading army.'},
      {id:'2-rescue',title:'Save the people on both sides',prompt:'Offer three jobs: anchor the bus, open an escape route, and hold the unstable boundary.',procedure:'Rescue task: 8 group Task Tokens in 4 rounds. Use appropriate Athletics, Electronics, Repair, or Persuasion actions; Persuasion can organize panicking people, not command physics. A falling-sign hazard occurs once in round 2: tell everyone beneath it first, then allow an Agility roll to get clear; failure deals 2d6 damage. Heroes who move civilians out of that area prevent it without damage rolls. Contractors arrive to seize Pip, one per hero. They prefer restraint and can be persuaded that evacuation outranks their order.',clue:'A contractor says, “They told us what would be damaged before the first call came in.”'},
      {id:'2-paper',title:'Follow the cleanup',prompt:'Put Handout 2 in front of the group.',procedure:'The dispatch paper is automatically available from an abandoned kit, a cooperative worker, or a supervisor’s public notice. Research verifies the order timing; a raise names a second matching job. A failure still confirms the before-and-after sequence but attracts Calder’s attention. Helping the contractors get home makes a crew contact available later. Defeating them yields the same paper, without the ally.',clue:'The job is profitable, predicted, and connected to Thompson.'},
    ],
    outcomes:{success:'Civilians escape and the boundary stabilizes. Pip or a contractor volunteers evidence.',partial:'Choose damaged property or a stranded civilian group. The crew gets the dispatch paper and can mount a second rescue.',failure:'A larger rescue is needed, not an erased population. A witness carries the paper to the crew. Record which people need help and move the investigation forward.'},
    next:'The players now know who profits. Let them choose the first investigative route in Session 3.'
  },
  {
    id:3,title:'Shake the Snow Globe',act:'Act II - Somebody owns this place',
    purpose:'Turn separate emergencies into an acquisition mystery without betting it on one roll.',
    readAloud:'The repair invoice is routine. Same company. Same surcharge. Same “unexpected” emergency. The delivery time is the strange part: the replacement supplies arrived before the city knew anything was broken.',
    essentialClues:['The municipal business profits from predicted shakes.', 'An external owner can move the city’s boundary; the human beneficiary is not the eligible bidder.'],
    clock:null,
    scenes:[
      {id:'3-routes',title:'Offer three ways into the pattern',prompt:'Records desk, repair depot, or incursion witness. Let the group choose.',procedure:'At the records desk, Inez shares public invoices; Research adds the matching shell account. At the depot, workers share the kit schedule; Stealth or Persuasion secures a private manifest. At the witness site, someone points out the equipment that pulsed just before the air changed; Electronics explains its connection to Thompson. Each route supplies the core pattern automatically. Failed rolls cost access, time, or discretion. Use contractors only if a confrontation develops; they are witnesses as well as obstacles.',clue:'Three incidents share an equipment serial and a Thompson control destination.'},
      {id:'3-shake',title:'Show the hand outside',prompt:'A window reflection shows the whole skyline tilted in a curved glass wall.',procedure:'An announced shake gives the crew a short rescue or observation choice. A hero who protects someone gets a clear view of the external shape; another can secure the equipment. Use an ordinary roll for either risky action. No roll is needed to understand that the event is deliberate. A failed observation still leaves a recording from a witness, but the crew is identified by the control network.',clue:'The incident is someone exercising a privilege, not a machine breaking at random.'},
      {id:'3-calder',title:'Confront the beneficiary',prompt:'Calder offers a job before he offers a threat.',procedure:'He says the city needs someone who can arrange reliable recovery. If exposed, he attempts to reach Thompson, where normal jurisdiction fails. Do not give him an automatic escape: capture, negotiation, surrender, or defeat are valid. If the players capture him, his key and the records direct them to Thompson anyway. If he dies, a deputy contractor has the routing order. A core Social Conflict or a short chase can resolve opposition; the result changes his leverage, not whether the maze exists.',clue:'Calder says someone else did the bidding and expects to be paid in “enrichment.”'},
    ],
    outcomes:{success:'The crew secures the key or a cooperative guide and enters Thompson with leverage.',partial:'Calder reaches Thompson first. The party has the destination and records, but custodians expect them.',failure:'The crew is publicly blamed for a disruption. Inez supplies a service entrance and proof. That accusation is fictional fallout; it cannot remove every action the players can take.'},
    next:'Give the second milestone Advance. Keep Calder’s fate and the workers’ loyalties when preparing the maze.'
  },
  {
    id:4,title:'The Thompson Center Maze',act:'Act II - Somebody owns this place',
    purpose:'Make the location reveal the purchase, the shaking rights, and a way to break the boundary.',
    readAloud:'The ticket says your number will be called shortly. It has been printed on a leaf, a boarding pass, and a municipal parking citation. Across the atrium, three offices occupy the same door. All three say you need the other office first.',
    essentialClues:['Up died accidentally; his estate auction sold the inhabited holding.', 'The Keeper’s compensation includes shaking rights.', 'The control seam can be cracked by a tuned beam without relocating Chicago.'],
    clock:{id:'maze',label:'Maze shift',max:4,trigger:'Fill one box for a repeated route without a changed method, or a delay the crew knowingly accepts.',consequence:'Custodians arrive, one per two heroes rounded up. Other routes remain open.'},
    scenes:[
      {id:'4-ticket',title:'Choose a route through jurisdiction',prompt:'Use the node map. Start at A and visibly offer B or C.',procedure:'Calder’s key admits the crew to one node without a roll. At B, an elven departures queue contains stranded travelers; helping them gains a transit badge and a route to D. At C, Inez or an estate clerk provides the ledger. A roll can speed either route or preserve discretion. Failure fills the shift clock once and opens the other route. Never send the party back to the start as its only consequence. Security can be persuaded, bypassed, or fought.',clue:'The bidder’s name and the beneficiary’s name occupy different columns.'},
      {id:'4-ledger',title:'Make the deal legible',prompt:'Reveal Handout 3. Answer questions plainly.',procedure:'An eligible higher-dimensional Keeper bid for Calder. The arrangement gave the Keeper Chicago as a living snow globe. Up’s death was a stupid accident; there is no murder solution hiding behind it. Research or Persuasion can discover a severance record or an enforcement weakness, but the central facts need no roll. If the crew tries a legal cancellation, let it suspend one shake or free one custodian. Complete invalidation of ownership still requires reaching the seam in this edition.',clue:'A person’s presence in a ledger does not make the ownership legitimate.'},
      {id:'4-seam',title:'Choose what to disable',prompt:'At D, offer the shake switch or the path to Calder. At E, offer the seam diagram.',procedure:'Electronics or Repair disables a local shake feed; a creative physical bypass can work too. Success prevents the first extra hazard at the accelerator. Failure costs a tool or brings a custodian; the seam diagram remains readable. It names the fictional Loop Resonance Works, and a clear note distinguishes cracking the ownership boundary from moving the city. A surviving Calder can bargain, surrender the key, or be escorted out. Keep choices about him in the players’ hands.',clue:'The heroes may be flung outside when the boundary breaks. Chicago can remain in Chicago.'},
    ],
    outcomes:{success:'The party has the diagram, route, and one disabled feed or allied custodian.',partial:'They have the route but must evacuate people or bring Calder with them.',failure:'They escape through a service passage with the essential diagram. Pursuit costs them the easy accelerator entrance; it does not hide the objective.'},
    next:'Ask who they want to protect when they fire. Prepare the accelerator around that choice.'
  },
  {
    id:5,title:'Crack the Bottle',act:'Act II - Somebody owns this place',
    purpose:'Give the whole party simultaneous jobs while freeing the city from ownership.',
    readAloud:'The control display shows a seam through the city, but the line belongs to something larger than the map. The engineer points to three feeds. “Power. Aim. Containment. You can get two wrong and still make a terrible noise.”',
    essentialClues:['The seam and the earthquake are different problems.', 'A correct shot severs ownership; the city does not have to leave its physical place.'],
    clock:{id:'quake',label:'Earthquake',max:6,trigger:'Fill one box after each activation round. Add one extra only for an explicitly announced containment mishap.',consequence:'A ground hazard strikes and evacuation becomes urgent. The team can still fire.'},
    scenes:[
      {id:'5-arrive',title:'Reach the fictional test hall',prompt:'Use Loop Resonance Works, a fictional installation. Show three feeds and two exits.',procedure:'Dr. Vale can explain the fantasy physics, but does not operate every station for the heroes. There is no real accelerator schematic or real-world firing procedure here. The group chooses power, calibration, containment, evacuation, and protection. An allied custodian holds an entrance; an allied contractor opens an exit. If the crew disabled Thompson’s shake feed, the first hazard is only a warning. Otherwise a falling panel threatens the service route: announce it and allow Athletics or Repair to protect that route.',clue:'The beam targets a higher-dimensional ownership seam, not residents or a real geological weapon.'},
      {id:'5-fire',title:'Activate under pressure',prompt:'Use a Dramatic Task alongside initiative for interference.',procedure:'Group goal: 12 Task Tokens in 4 rounds. Electronics calibrates or energizes; Repair contains; Athletics braces; Persuasion organizes evacuation. Each action needs a concrete job. Support works normally and does not itself earn tokens. Two rift leeches interfere in round 2; contractors equal to half the heroes, rounded up, arrive in round 3 unless an ally or agreement keeps them away. Fill one earthquake box after each round. Announce a containment mishap before a risky attempt; a Critical Failure on that attempt adds one extra box as well as the core task consequence. Apply other core complications normally.',clue:'The seam display opens a channel out of the bottle as calibration approaches its goal.'},
      {id:'5-break',title:'Choose a cost and let the world open',prompt:'At the task’s end, resolve the seam and quake separately.',procedure:'If the goal is reached, the seam cracks. If not, allow one clearly offered emergency firing: it cracks the seam at the cost of damaging the hall and filling the earthquake clock. A crew that refuses can evacuate, regroup, and retry with a portable salvaged feed; this costs a scene, not a new campaign. At six quake boxes, everyone in an exposed area gets one announced Agility roll to reach cover; failure deals 2d6 damage. A successful evacuation action protects the civilians automatically. The boundary then throws the heroes onto a service platform outside. The city remains where it belongs.',clue:'An auction service plate on the platform can become a vessel and a route instrument.'},
    ],
    outcomes:{success:'Chicago is freed; the heroes reach the archipelago with a stable vessel component.',partial:'The city is freed with repair needs or missing equipment. Allies evacuate survivors; the voyage has an extra repair beat.',failure:'An emergency firing or second attempt frees the city at a severe local cost. If the party declines both, use the retreat and retry route. Do not narrate them into an action they refused.'},
    next:'Give the third milestone Advance. Describe the primordial sea and let the players name their improvised vessel.'
  },
  {
    id:6,title:'Adrift in the Universe',act:'Act III - Adrift, then home',
    purpose:'Teach timed crossings while making outside realities into places with people.',
    readAloud:'The platform floats above a foggy sea. Far away, a school, a wood, and a lit train carriage drift on separate horizons. Your route instrument pulses once. Mark stops talking. “We have until the third one.”',
    essentialClues:['Every useful slide has a brief window and needs an anchor at both ends.', 'A home signal can use a chosen Chicago place as its address.'],
    clock:{id:'slide',label:'Slide departure',max:6,trigger:'Fill one box after each meaningful travel beat or local choice, not after each individual roll.',consequence:'The window closes. Wait for the next one with a cost, or use another island route.'},
    scenes:[
      {id:'6-vessel',title:'Build a way to travel',prompt:'Turn the auction platform into a skiff, ferry, or other group-chosen vessel.',procedure:'Establish a power source, a steerable surface, and a route instrument. Each needs one suitable successful Trait roll, with Support welcome. A failure adds a repair beat and a chosen limitation, not destruction. Mark can energize a compatible component while a hero navigates or repairs; another electrical or mechanical method works if he is absent. Reveal Handout 4. The foggy sea is fantastical; do not impose realistic cryogenic lethality on this adapted novel imagery.',clue:'A place the players named in Session 0 is recognizable as a destination signal.'},
      {id:'6-islands',title:'Choose two stops, not a tour checklist',prompt:'Offer the stranded train, elven departures, and the auction dock. The crew chooses its route.',procedure:'At the train, saving passengers costs two beats and earns a signal lamp; leaving costs one and leaves an ally unresolved. At departures, two custodians demand a badge; negotiation, showing the ledger, or a short fight earns a route stamp. At the dock, an abandoned lot offers spare anchors; searching costs a beat, and the repossessor can offer a shortcut in exchange for a future ownership claim. Let players reject it. Each local problem uses one or two ordinary rolls or a core Quick Encounter. Reset the slide clock when arriving at a new stop.',clue:'The lamp, stamp, or anchor identifies a home route. Any one supplies the essential direction; two make the finale’s first calibration easier.'},
      {id:'6-cross',title:'Leave before the slide closes',prompt:'Show six boxes and state the current departure pressure.',procedure:'Crossing uses one navigation roll and one anchoring roll, with suitable skills and Support. Success and failure change the crossing’s cost. At six boxes, the current window closes: wait for the next cycle and add a repair or rescue problem, or go by the other offered route. If both anchors are lost, the crew is marooned between realities; a visible drifting cable can be caught with Athletics, or an ally can pull them to a nearby island. No single failed roll ends the voyage. End when they know the home signal and see the final route.',clue:'Getting home must not reconstruct the city’s enclosure.'},
    ],
    outcomes:{success:'The crew has a clear home signal and two helpful preparations.',partial:'They have the signal with damaged gear or an ally to return for. Preserve that promise for the epilogue.',failure:'A missed slide changes the route. They recover at another island, obtain the signal from a beacon, and begin Session 7 with one repair beat.'},
    next:'Ask what message the crew wants Chicago to hear. Make it the centerpiece of the final gathering.'
  },
  {
    id:7,title:'Message in a Bottle',act:'Act III - Adrift, then home',
    purpose:'Pay off the voyage and the electrical motif without returning the city to captivity.',
    readAloud:'The city answers your signal. There are people at the other end, not a glass wall. A second voice interrupts: “We can make your passage quite safe. All we need is the old boundary.”',
    essentialClues:['The Keeper’s safe passage bargain would restore ownership.', 'The tether is a mechanism the heroes can disable, not an invincible monster to defeat.'],
    clock:{id:'tether',label:'Final tether',max:4,trigger:'Fill one box after a finale round while the tether remains active.',consequence:'The repossessor boards. Disabling the tether remains available.'},
    scenes:[
      {id:'7-message',title:'Make home recognize them',prompt:'Ask each hero for one line of the message and one contribution to the crossing.',procedure:'The route requires the group’s chosen place name and three long flashes plus one short. Electronics, Repair, Persuasion, or a justified other skill can send, stabilize, or coordinate the signal. If the crew gained two preparations in Session 6, give +1 to the first calibration attempt. If Mark is a player, let that player choose the electrical contribution; if he is an NPC, he supplies current while the heroes make the decisions. Missing gear can be replaced with a visible cable and one repair beat.',clue:'Residents on the other side can anchor the destination without enclosing it.'},
      {id:'7-claim',title:'Resist the last claim',prompt:'The repossessor attaches a visible tether. Put its target terminal within reach.',procedure:'The agent offers safe passage for a renewed boundary, then attempts enforcement if refused. Use its original profile. The heroes may fight, bargain for time, demonstrate the severance, or disable the tether with Electronics or Repair at -2. The terminal has Toughness 6 and can be broken; no need to kill the agent. The task to align and cross requires 8 group Task Tokens in 3 rounds using core rules. A hero who addresses the tether has a clear competing job; Support counts normally. Fill the four-box tether clock only while the anchor remains attached.',clue:'The agent’s legal assumption can be rejected; the city’s people are not valid collateral.'},
      {id:'7-home',title:'Resolve the crossing, then listen',prompt:'Use the crew’s actual choices to determine the ending.',procedure:'Goal met with tether disabled: return freely. Goal met with tether active: the bow crosses but the vessel remains held; residents help stabilize it while the heroes take one last scene to sever the terminal or force a release. Goal missed: the final window closes, leaving an anchored island and a new cycle; accept a damaged vessel or a delayed homecoming, then try again after a concrete repair. A crew that accepts the bad bargain gets a compromised ending, with the ownership problem explicitly unresolved. Do not call that freedom. At home, ask each player for one changed relationship and one place they visit first.',clue:'The intended victory is freedom plus homecoming. A warm welcome cannot hide a renewed cage.'},
    ],
    outcomes:{success:'Chicago is safe because it belongs to its people. The heroes return, and residents publicly acknowledge what they did.',partial:'The city is free; the heroes return later or with damage, and keep a promise to rescue an ally. Give them a route to honor it.',failure:'They remain temporarily anchored outside, or knowingly accept the Keeper’s bargain. State the cost honestly. Offer the repair-and-retry route; never turn one unlucky roll into an unannounced total-party death.'},
    next:'Close on player epilogues. Record which places, people, and promises survived. Ask what should change before anyone calls this edition playtested.'
  }
];
